name: mnid_dart
description: Multi Network Identifier - spec and reference implementation
version: 0.1.3
repository: https://github.com/fuseio/mnid_dart
homepage: https://fuse.io

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  base_x: ^2.0.0
  collection: ^1.17.2
  hex: ^0.2.0
  sha3: ^0.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.4
