name: mnid_dart
description: Multi Network Identifier - spec and reference implementation
version: 0.1.5
repository: https://github.com/fuseio/mnid_dart
homepage: https://fuse.io

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  base_x: ^2.0.1
  collection: ^1.18.0
  hex: ^0.2.0
  sha3: ^0.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
